CPP-990 Add brief section on OpenSSL 3.x to building doc
datastax/cpp-driver pull request #557
Opened 2023-09-19 20:55 UTC by absurdfarce

2023-09-19 20:56 UTC, absurdfarce commented on topics/building/README.md
> +
@emeliawilkinson24 and @weideng1: I'm not 💯 convinced this paragraph is actually useful.  The same information is provided in more detail in the comments of [CPP-990](https://datastax-oss.atlassian.net/browse/CPP-990) and I'm not sure a paragraph like the one above gives the user any tools to make their experience with the driver better.

2023-09-22 22:08 UTC, weideng1 approved these changes
Good explanation of the background with the additional paragraph you added. LGTM

2023-09-27 13:38 UTC, emeliawilkinson24 requested changes

2023-09-28 21:49 UTC, absurdfarce commented on topics/building/README.md
> +* [OpenSSL] v1.0.x, v1.1.x or v3.x \*\*
Wait, are we gonna have to duke it out about the Harvard comma now? :)

2023-09-28 21:52 UTC, absurdfarce commented on topics/building/README.md
> +Migrating from OpenSSL 1.1.x to 3.x largely involves avoiding the use of many functions which are now deprecated (consult
I don't think this one quite works.  "Migrating from OpenSSL X to Y avoids using many functions which are now deprecated" seems wrong.  The intent is to communicate what migration involves, not the effect of migration.

2023-09-28 22:06 UTC, absurdfarce commented on topics/building/README.md
> +
That makes sense to me @emeliawilkinson24 .  After the other edits you had on your review I _think_ we can get to something I can live with if I just remove that last sentence.  I'll give it a shot and see what it looks like.

2023-09-28 22:09 UTC, absurdfarce commented on topics/building/README.md
> +
Okay, I liked how things look with that sentence out.  Take another pass when you have some time @emeliawilkinson24 and let me know what you think!

2023-09-29 13:08 UTC, emeliawilkinson24 approved these changes
LGTM

2023-09-29 15:35 UTC, merged